version: 2
jobs:

  unit-tests:
    docker:
      - image: crystallang/crystal:0.31.1
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install curl libsqlite3-dev -y
      - run: |
          shards build --release
          crystal spec

workflows:
  version: 2

  hosted-danger-workflow:

    jobs:
      - unit-tests
